Add max length for the slug
qqilihq/mongoose-slugger pull request #43
Opened 2023-01-25 17:10 UTC by Arsalanliaqat

2023-01-25 17:49 UTC, qqilihq requested changes

2023-01-25 17:49 UTC, qqilihq commented on lib/slugger.ts
> +  readonly maxLength?: number;
Add a validation that `maxLength` has reasonable value (i.e. > 0)

2023-01-25 17:50 UTC, qqilihq commented
Thank you, Arslan. Beside the comments above, could you please add test cases which cover the new maxLength functionality? As far as I can see there were some in the older branch which I once did, probably you can just copy these.

2023-01-26 09:17 UTC, Arsalanliaqat commented on lib/sluggerUtils.ts
> +    return maxLength && maxLength > 0 ? trimSlug(slug, maxLength) : slug;
What do you suggest here? Does it make sense to trim from the middle section of the string?

`this-is-another-valid-example-of-a-very-very-long-slug-1` to something like this `this-is-another-very-long-slug-1`.

2023-01-26 09:53 UTC, qqilihq commented on lib/sluggerUtils.ts
> +    return maxLength && maxLength > 0 ? trimSlug(slug, maxLength) : slug;
Let's just trim the original string, and then add the running index if needed. Eg. slug length is 30 characters:

`this-is-another-valid-example-of-a-very-very-long-slug-1` -> `this-is-another-valid-examp-1`

2023-01-26 12:45 UTC, qqilihq commented on readme.md
> +  maxLength: 0,
Give a valid example here

2023-01-26 12:46 UTC, qqilihq commented
Hey Arslan - when I currently run the tests locally, one of them fails. Does it work for you? Could you look into this?

```
  ● slugger › saving to database › generating duplicate slugs within one sequence › throws when same slugs are generated within one save cycle

    expect(received).toBeInstanceOf(expected)

    Expected constructor: SluggerError
    Received constructor: ReferenceError

      487 |           fail();
      488 |         } catch (e) {
    > 489 |           expect(e).toBeInstanceOf(slugger.SluggerError);
          |                     ^
      490 |           expect((e as slugger.SluggerError).message).toEqual("Already attempted slug 'john' before. Giving up.");
      491 |         }
      492 |       });
```

2023-01-26 12:48 UTC, qqilihq commented
One more thing: As far as I read the code, you currently take the `maxLength` either from the slugger options or directly from the schema. That's cool, but could you explicitly document this in the readme?

2023-01-26 13:07 UTC, Arsalanliaqat commented
> Hey Arslan - when I currently run the tests locally, one of them fails. Does it work for you? Could you look into this?
> 
> ```
>   ● slugger › saving to database › generating duplicate slugs within one sequence › throws when same slugs are generated within one save cycle
> 
>     expect(received).toBeInstanceOf(expected)
> 
>     Expected constructor: SluggerError
>     Received constructor: ReferenceError
> 
>       487 |           fail();
>       488 |         } catch (e) {
>     > 489 |           expect(e).toBeInstanceOf(slugger.SluggerError);
>           |                     ^
>       490 |           expect((e as slugger.SluggerError).message).toEqual("Already attempted slug 'john' before. Giving up.");
>       491 |         }
>       492 |       });
> ```

This is strange; It works fine for me.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/37035310/214842921-86c7f364-a66b-4d57-93de-dd3922d11319.png">

2023-01-26 15:43 UTC, merged